services:
    mysql:
        image: mysql:8.1.0
        restart: "no"
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d:ro
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
    redis:
        image: redis:7.4.0
        restart: "no"
        ports:
            - "6379:6379"
volumes:
    mysql_data:
